name: "Legacy League Discord Bot"
version: "1.0.5"
slug: "legacy-league-bot"
description: "Discord bot for Legacy League with player value calculation and event management"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
ingress: true
ingress_port: 3000
ingress_entry: /
panel_icon: mdi:discord
panel_title: "Legacy League Bot"
panel_admin: true
ports:
  3000/tcp: 3000
map:
  - config:rw
  - ssl:ro
environment:
  NODE_ENV: production
options:
  discord_token: ""
  log_level: info
schema:
  discord_token: str
  log_level: list(debug|info|warning|error|critical) 